services:
  # Backend API Service
  - type: web
    name: marketing-automation-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: marketing-automation-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: marketing-automation-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          type: web
          name: marketing-automation-frontend
          property: url
      - key: BACKEND_URL
        fromService:
          type: web
          name: marketing-automation-api
          property: url
      - key: COHERE_API_KEY
        sync: false
      - key: FACEBOOK_ACCESS_TOKEN
        sync: false
      - key: LINKEDIN_ACCESS_TOKEN
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

  # Frontend Static Site
  - type: web
    name: marketing-automation-frontend
    env: static
    buildCommand: ""
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Redis Instance
  - type: redis
    name: marketing-automation-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free

# Database
databases:
  - name: marketing-automation-db
    databaseName: marketing_automation
    user: marketing_automation
    plan: free 